"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .sdkerror import SDKError
from typing import Any, TYPE_CHECKING

from openapi.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .errors_errorresponse import ErrorsErrorResponse, ErrorsErrorResponseData
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError
    from .sdkdefaulterror import SDKDefaultError

__all__ = [
    "ErrorsErrorResponse",
    "ErrorsErrorResponseData",
    "NoResponseError",
    "ResponseValidationError",
    "SDKDefaultError",
    "SDKError",
]

_dynamic_imports: dict[str, str] = {
    "ErrorsErrorResponse": ".errors_errorresponse",
    "ErrorsErrorResponseData": ".errors_errorresponse",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKDefaultError": ".sdkdefaulterror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
