"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import UnrecognizedStr
from typing import Literal, Union


TypesInvoiceCadence = Union[
    Literal[
        "ARREAR",
        "ADVANCE",
    ],
    UnrecognizedStr,
]
