"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from openapi import models
from openapi._hooks import SDKHooks
from openapi.types import OptionalNullable, UNSET
import sys
from typing import Any, Callable, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from openapi.addons import Addons
    from openapi.alerts import Alerts
    from openapi.costs import Costs
    from openapi.coupons import Coupons
    from openapi.credit_grants import CreditGrants
    from openapi.credit_notes import CreditNotes
    from openapi.customers import Customers
    from openapi.entitlements import Entitlements
    from openapi.entity_integration_mappings import EntityIntegrationMappings
    from openapi.environments import Environments
    from openapi.events import Events
    from openapi.features import Features
    from openapi.groups import Groups
    from openapi.integrations import Integrations
    from openapi.invoices import Invoices
    from openapi.payments import Payments
    from openapi.plans import Plans
    from openapi.price_units import PriceUnits
    from openapi.prices import Prices
    from openapi.rbac import Rbac
    from openapi.scheduled_tasks import ScheduledTasks
    from openapi.secrets import Secrets
    from openapi.subscriptions import Subscriptions
    from openapi.tasks import Tasks
    from openapi.tax_associations import TaxAssociations
    from openapi.tax_rates import TaxRates
    from openapi.tenants import Tenants
    from openapi.users import Users
    from openapi.wallets import Wallets
    from openapi.webhooks import Webhooks
    from openapi.workflows import Workflows


class SDK(BaseSDK):
    r"""Flexprice API: Flexprice API provides billing, metering, and subscription management for SaaS and usage-based products. Use it to manage customers, plans, invoices, payments, usage events, and entitlements. Authenticate with an API key in the x-api-key header."""

    addons: "Addons"
    entitlements: "Entitlements"
    alerts: "Alerts"
    costs: "Costs"
    coupons: "Coupons"
    credit_grants: "CreditGrants"
    credit_notes: "CreditNotes"
    customers: "Customers"
    wallets: "Wallets"
    invoices: "Invoices"
    entity_integration_mappings: "EntityIntegrationMappings"
    environments: "Environments"
    events: "Events"
    features: "Features"
    groups: "Groups"
    payments: "Payments"
    plans: "Plans"
    prices: "Prices"
    price_units: "PriceUnits"
    rbac: "Rbac"
    secrets: "Secrets"
    integrations: "Integrations"
    subscriptions: "Subscriptions"
    tasks: "Tasks"
    scheduled_tasks: "ScheduledTasks"
    tax_associations: "TaxAssociations"
    tax_rates: "TaxRates"
    tenants: "Tenants"
    users: "Users"
    webhooks: "Webhooks"
    workflows: "Workflows"
    _sub_sdk_map = {
        "addons": ("openapi.addons", "Addons"),
        "entitlements": ("openapi.entitlements", "Entitlements"),
        "alerts": ("openapi.alerts", "Alerts"),
        "costs": ("openapi.costs", "Costs"),
        "coupons": ("openapi.coupons", "Coupons"),
        "credit_grants": ("openapi.credit_grants", "CreditGrants"),
        "credit_notes": ("openapi.credit_notes", "CreditNotes"),
        "customers": ("openapi.customers", "Customers"),
        "wallets": ("openapi.wallets", "Wallets"),
        "invoices": ("openapi.invoices", "Invoices"),
        "entity_integration_mappings": (
            "openapi.entity_integration_mappings",
            "EntityIntegrationMappings",
        ),
        "environments": ("openapi.environments", "Environments"),
        "events": ("openapi.events", "Events"),
        "features": ("openapi.features", "Features"),
        "groups": ("openapi.groups", "Groups"),
        "payments": ("openapi.payments", "Payments"),
        "plans": ("openapi.plans", "Plans"),
        "prices": ("openapi.prices", "Prices"),
        "price_units": ("openapi.price_units", "PriceUnits"),
        "rbac": ("openapi.rbac", "Rbac"),
        "secrets": ("openapi.secrets", "Secrets"),
        "integrations": ("openapi.integrations", "Integrations"),
        "subscriptions": ("openapi.subscriptions", "Subscriptions"),
        "tasks": ("openapi.tasks", "Tasks"),
        "scheduled_tasks": ("openapi.scheduled_tasks", "ScheduledTasks"),
        "tax_associations": ("openapi.tax_associations", "TaxAssociations"),
        "tax_rates": ("openapi.tax_rates", "TaxRates"),
        "tenants": ("openapi.tenants", "Tenants"),
        "users": ("openapi.users", "Users"),
        "webhooks": ("openapi.webhooks", "Webhooks"),
        "workflows": ("openapi.workflows", "Workflows"),
    }

    def __init__(
        self,
        server_url: str,
        api_key_auth: Union[str, Callable[[], str]],
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param api_key_auth: The api_key_auth required for authentication
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        security: Any = None
        if callable(api_key_auth):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: models.Security(api_key_auth=api_key_auth())
        else:
            security = models.Security(api_key_auth=api_key_auth)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
